before_script:
    - echo "$SSH_KEY" | tr -d '\r' > key.pub
    - chmod 400 key.pub

dev_deploy:
    stage: deploy
    script:
        - ssh -o "StrictHostKeyChecking no" -i key.pub $DEV_CONNECTION "cd $PROJECT_DIR && git pull https://$GIT_USERNAME:$GIT_PASSWORD@git.codebusters.team/gamisoft/gamisoft.git"
        - ssh -o "StrictHostKeyChecking no" -i key.pub $DEV_CONNECTION "cd $PROJECT_DIR && npm install --allow-root"
        - ssh -o "StrictHostKeyChecking no" -i key.pub $DEV_CONNECTION "cd $PROJECT_DIR && npm run predeploy"
    when: on_success
    only:
        - master
    tags:
        - shell
