import { TableWithCheckboxes } from 'src/components/molecules/Table';
import { CourseDetailTypes, Status, ProgressStatus } from 'src/store/course/types';
import Img from 'src/assets/img/mocks/36px.png'

export const COURSES: TableWithCheckboxes<CourseDetailTypes.IRenderProps>[] = [
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 41,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.DRAFT,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 42,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.PUBLISHED,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 43,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.DRAFT,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 44,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.DRAFT,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 45,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.DRAFT,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
  {
    cardIds: [],
    certificateExpirationDate: 0,
    certificateImageThumbnailUrl: '',
    certificateImageUrl: '',
    commentsAmount: 0,
    companyId: 1,
    createdAt: '2021-02-09T10:28:40.432610',
    curUrl: '#',
    description: 'Кассовые операции команда 123 BI Group ',
    examStatus: ProgressStatus.NOT_STARTED,
    finalResultCertificateId: undefined,
    groupIds: [],
    groups: [
      {
        id: 1,
        name: 'Разработчкии',
        type: '',
      },
    ],
    id: 46,
    imageThumbnailUrl: Img,
    imageUrl: Img,
    isFavorite: false,
    isFinished: false,
    minutesToFinish: 2,
    modules: [],
    name: 'Кассовые операции команда 123 BI Group ',
    numberOfViews: 0,
    progress: 0,
    rating: 0,
    rewardAmount: 1250,
    status: Status.DRAFT,
    tagIds: [42],
    tags: [],
    userRating: 3,
    uuid: '',
  },
];
