import 'src/i18n';
import { configure as storyConfigure } from '@storybook/react';
import 'src/assets/scss/main.scss';

storyConfigure(() => {
  require('src/components/atoms/Button/stories');
  require('src/components/atoms/Cards/CardBadge/stories');
  require('src/components/molecules/Cards/CardBattle/stories');
  require('src/components/molecules/Cards/CardCompanyChoice/stories');
  require('src/components/atoms/Cards/CardInformation/stories');
  require('src/components/molecules/Cards/CardGame/stories');
  require('src/components/molecules/Cards/CardRate/stories');
  require('src/components/atoms/Cards/CardInputSearcher/stories');
  require('src/components/molecules/Cards/CardEducation/stories');
  require('src/components/atoms/Cards/CardTask/stories');
  require('src/components/atoms/Cards/CardTotalAmountBranches/stories');
  require('src/components/atoms/Cards/CardUserAchievement/stories');
  require('src/components/atoms/Cards/CardUserStatistics/stories');
  require('src/components/atoms/Cards/CardNews/stories');
  require('src/components/molecules/Checkbox/stories');
  require('src/components/atoms/IconCertificate/stories');
  require('src/components/atoms/ImageCertificate/stories');
  require('src/components/molecules/Input/stories');
  require('src/components/molecules/InputTextSms/stories');
  require('src/components/molecules/Nav/stories');
  require('src/components/atoms/RadioButton/stories');
  require('src/components/atoms/Typography/stories');
  require('src/components/atoms/ProgressBar/stories');
  require('src/components/atoms/Loader/stories');
  require('src/components/atoms/LogoLoader/stories');
  require('src/components/molecules/Notification/stories.tsx');
  require('src/components/atoms/Section/stories.tsx');
  require('src/components/atoms/Svg/stories');
  require('src/components/molecules/AudioPlayer/stories');
  require('src/components/molecules/Cards/CardAdvertisement/stories');
  require('src/components/molecules/Cards/CardUserChangePassword/stories');
  require('src/components/molecules/Cards/CardUserEditing/stories');
  require('src/components/molecules/CodeSelect/stories');
  require('src/components/molecules/DatePicker/stories');
  require('src/components/molecules/DropZone/stories');
  require('src/components/organisms/Layout/stories');
  require('src/components/molecules/Select/stories');
  require('src/components/molecules/Sidebar/stories');
  require('src/components/molecules/UserActivityTasks/stories');
  require('src/components/molecules/TreeSelect/stories');
  require('src/components/molecules/BranchesStructure/stories');
  require('src/components/molecules/Chips/stories');
  require('src/components/molecules/RubricTree/stories');
  require('src/components/molecules/DateRangePicker/stories');
  require('src/components/atoms/Stepper/stories');
},             module);
