import { MarketPlaceShellTypes } from './types';

export const Marketplaces: MarketPlaceShellTypes.IMarket[] = [
  {
    id: 1,
    image: '',
    title: 'Borderlands',
    description: 'В данном разделе вы можете создавать, удалять и редактировать: задания, игры...',
    rate: 4,
    commentCount: 10,
    cost: 1000,
    status: 'buy',
  },
  {
    id: 2,
    image: '',
    title: 'Anthem',
    description: 'В данном разделе вы можете создавать, удалять и редактировать: задания, игры...',
    rate: 4,
    commentCount: 10,
    cost: 1000,
    status: 'bought',
  },
  {
    id: 3,
    image: '',
    title: 'Kingdom Defender',
    description: 'В данном разделе вы можете создавать, удалять и редактировать: задания, игры...',
    rate: 4,
    commentCount: 10,
    cost: 1000,
    status: 'buy',
  },
  {
    id: 4,
    image: '',
    title: 'Footbool Leage 2',
    description: 'В данном разделе вы можете создавать, удалять и редактировать: задания, игры...',
    rate: 4,
    commentCount: 10,
    cost: 1000,
    status: 'buy',
  },
  {
    id: 5,
    image: '',
    title: 'Borderlands',
    description: 'В данном разделе вы можете создавать, удалять и редактировать: задания, игры...',
    rate: 4,
    commentCount: 10,
    cost: 1000,
    status: 'buy',
  },
];
